/** @type {import('tailwindcss').Config} */
module.exports = {
 darkMode: "class",
 content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-100": "var(--error-100)",
        "error-1000": "var(--error-1000)",
        "error-200": "var(--error-200)",
        "error-300": "var(--error-300)",
        "error-400": "var(--error-400)",
        "error-500": "var(--error-500)",
        "error-600": "var(--error-600)",
        "error-700": "var(--error-700)",
        "error-800": "var(--error-800)",
        "error-900": "var(--error-900)",
        "neutral-scale100": "var(--neutral-scale100)",
        "neutral-scale1000": "var(--neutral-scale1000)",
        "neutral-scale1100": "var(--neutral-scale1100)",
        "neutral-scale1200": "var(--neutral-scale1200)",
        "neutral-scale1300": "var(--neutral-scale1300)",
        "neutral-scale1400": "var(--neutral-scale1400)",
        "neutral-scale1500": "var(--neutral-scale1500)",
        "neutral-scale1600": "var(--neutral-scale1600)",
        "neutral-scale1700": "var(--neutral-scale1700)",
        "neutral-scale1800": "var(--neutral-scale1800)",
        "neutral-scale200": "var(--neutral-scale200)",
        "neutral-scale300": "var(--neutral-scale300)",
        "neutral-scale400": "var(--neutral-scale400)",
        "neutral-scale500": "var(--neutral-scale500)",
        "neutral-scale600": "var(--neutral-scale600)",
        "neutral-scale70": "var(--neutral-scale70)",
        "neutral-scale700": "var(--neutral-scale700)",
        "neutral-scale80": "var(--neutral-scale80)",
        "neutral-scale800": "var(--neutral-scale800)",
        "neutral-scale90": "var(--neutral-scale90)",
        "neutral-scale900": "var(--neutral-scale900)",
        "primery-100": "var(--primery-100)",
        "primery-1000": "var(--primery-1000)",
        "primery-200": "var(--primery-200)",
        "primery-300": "var(--primery-300)",
        "primery-400": "var(--primery-400)",
        "primery-500": "var(--primery-500)",
        "primery-600": "var(--primery-600)",
        "primery-700": "var(--primery-700)",
        "primery-800": "var(--primery-800)",
        "primery-90": "var(--primery-90)",
        "primery-900": "var(--primery-900)",
        "success-100": "var(--success-100)",
        "success-1000": "var(--success-1000)",
        "success-200": "var(--success-200)",
        "success-300": "var(--success-300)",
        "success-400": "var(--success-400)",
        "success-500": "var(--success-500)",
        "success-600": "var(--success-600)",
        "success-700": "var(--success-700)",
        "success-800": "var(--success-800)",
        "success-900": "var(--success-900)",
        "warning-100": "var(--warning-100)",
        "warning-1000": "var(--warning-1000)",
        "warning-200": "var(--warning-200)",
        "warning-300": "var(--warning-300)",
        "warning-400": "var(--warning-400)",
        "warning-500": "var(--warning-500)",
        "warning-600": "var(--warning-600)",
        "warning-700": "var(--warning-700)",
        "warning-800": "var(--warning-800)",
        "warning-900": "var(--warning-900)",
      },
      fontFamily: {
        vazir: ["Vazirmatn", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        "EN-inter-body-body": "var(--EN-inter-body-body-font-family)",
        "EN-inter-body-body-large":
          "var(--EN-inter-body-body-large-font-family)",
        "EN-inter-body-body-medium":
          "var(--EN-inter-body-body-medium-font-family)",
        "EN-inter-caption-1": "var(--EN-inter-caption-1-font-family)",
        "EN-inter-caption-2": "var(--EN-inter-caption-2-font-family)",
        "EN-inter-caption-3": "var(--EN-inter-caption-3-font-family)",
        "EN-inter-caption-4": "var(--EN-inter-caption-4-font-family)",
        "EN-inter-caption-5": "var(--EN-inter-caption-5-font-family)",
        "EN-inter-caption-6": "var(--EN-inter-caption-6-font-family)",
        "EN-inter-display": "var(--EN-inter-display-font-family)",
        "EN-inter-titles-1": "var(--EN-inter-titles-1-font-family)",
        "EN-inter-titles-2": "var(--EN-inter-titles-2-font-family)",
        "EN-inter-titles-3": "var(--EN-inter-titles-3-font-family)",
        "FA-vazirmatn-body-body": "var(--FA-vazirmatn-body-body-font-family)",
        "FA-vazirmatn-body-body-large":
          "var(--FA-vazirmatn-body-body-large-font-family)",
        "FA-vazirmatn-body-body-medium":
          "var(--FA-vazirmatn-body-body-medium-font-family)",
        "FA-vazirmatn-caption-1": "var(--FA-vazirmatn-caption-1-font-family)",
        "FA-vazirmatn-caption-2": "var(--FA-vazirmatn-caption-2-font-family)",
        "FA-vazirmatn-caption-3": "var(--FA-vazirmatn-caption-3-font-family)",
        "FA-vazirmatn-caption-4": "var(--FA-vazirmatn-caption-4-font-family)",
        "FA-vazirmatn-caption-5": "var(--FA-vazirmatn-caption-5-font-family)",
        "FA-vazirmatn-caption-6": "var(--FA-vazirmatn-caption-6-font-family)",
        "FA-vazirmatn-display": "var(--FA-vazirmatn-display-font-family)",
        "FA-vazirmatn-titles-1": "var(--FA-vazirmatn-titles-1-font-family)",
        "FA-vazirmatn-titles-2": "var(--FA-vazirmatn-titles-2-font-family)",
        "FA-vazirmatn-titles-3": "var(--FA-vazirmatn-titles-3-font-family)",
      },
      boxShadow: {
        "effects-drop-shadow-bottom": "var(--effects-drop-shadow-bottom)",
        "effects-drop-shadow-top": "var(--effects-drop-shadow-top)",
      },
    },
  },
  plugins: [],
};
